# Generated by Django 5.0.1 on 2024-03-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VibeMeet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default='0228c82b', max_length=8, unique=True),
        ),
    ]
